title: Ishan Bakshi # your name (or website title) here
logo: "/profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 Senior Quality Engineer
  <br><br>
  <a href="mailto:ishanbakshi91@gmail.com">ishanbakshi91@gmail.com </a>
  <br>
  <a href="https://www.linkedin.com/in/ishanbakshi/">LinkedIn Profile</a>
  <br>
  <a href="https://www.gihub.com/ishanbakshi91/">Gihub</a> 
theme: jekyll-theme-minimal
